[package]
name = "dumpgpt-rs"
version = "0.1.5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2"
bincode = "1.3.3"
serde = { version = "1.0.192", features = ["derive"] }
